spring.application.name=TouristPlanner
spring.datasource.url=jdbc:postgresql://localhost:5432/touristplanner
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=change-me-in-production-use-long-random-string
security.jwt.expiration-days=1

openrouteservice.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImRmM2E4NTdhYmEyNDRlY2Y4Yjc2ZjE4YjVmMjVhNjg3IiwiaCI6Im11cm11cjY0In0=
